name 'spring-boot'
maintainer 'Guido Schöninig'
maintainer_email 'guido.schoening@gmail.com'
license 'Apache-2.0'
description 'Installs/Configures spring-boot-app'
version '1.1.5'
chef_version '>= 12.5'
supports 'ubuntu'
supports 'centos'

source_url 'https://github.com/goblin23/chef-spring-boot'
issues_url 'https://github.com/goblin23/chef-spring-boot/issues'
